# ScreenMailer 配置文件
# 请根据您的实际情况修改此配置

# 邮件相关配置
email:
  # SMTP服务器设置
  smtp_server: smtp.example.com  # 您的SMTP服务器地址
  smtp_port: 587                 # 常用端口：587(TLS)或465(SSL)
  use_ssl: false                 # 是否使用SSL连接，根据您的邮件服务器要求设置
  
  # 登录凭证
  username: your_email@example.com  # 您的邮箱地址
  password: your_password_here      # 您的邮箱密码或应用专用密码
  
  # 发件人设置
  sender_email: your_email@example.com  # 发件人邮箱，通常与username相同
  
  # 收件人列表
  recipients:
    - recipient1@example.com      # 收件人邮箱
    - recipient2@example.com      # 可添加多个收件人
  
  # 邮件主题前缀
  subject_prefix: '[ScreenMailer]'  # 所有邮件主题的前缀

# 屏幕截图配置
screenshot:
  # 图片格式: png, jpg, jpeg, etc.
  format: png
  
  # 图片质量(仅对jpg格式有效): 0-100
  quality: 90
  
  # 截图区域，设置为null则截取全屏
  # bbox格式: [left, top, right, bottom]
  bbox: null

# 任务调度配置
scheduler:
  # 截图间隔时间(秒)
  screenshot_interval: 300       # 默认5分钟截图一次
  
  # 每次任务执行时连续截取的截图数量
  screenshot_count: 1
  
  # 连续截图之间的间隔时间(秒)
  screenshot_delay: 0.5
  
  # 邮件发送模式:
  # - interval: 按时间间隔发送
  # - hourly: 每小时整点发送
  # - half_hourly: 每半小时发送(xx:00和xx:30)
  # - custom: 自定义时间发送
  email_mode: interval
  
  # 邮件发送间隔时间(秒)，当email_mode为interval时使用
  email_interval: 3600          # 默认1小时发送一次
  
  # 自定义邮件发送时间，当email_mode为custom时使用
  # 格式为24小时制的HH:MM，例如：09:30, 18:00
  email_custom_times:
    - "09:00"
    - "12:00"
    - "18:00"
  
  # 是否在启动时立即执行一次任务
  send_immediate: true
  
  # 是否在截图后立即发送邮件
  # true: 每次截图后都立即发送邮件
  # false: 按照email_mode指定的时间发送累积的截图
  send_with_capture: false